worker_processes auto;
events { worker_connections 1024; }

http {
    upstream lux-backend { server luxstudio-backend:8750; }
    upstream gisvial-backend  { server gisvial-backend:8733; }
    upstream portal { server portal:80; }

    server {
        listen 80;
        server_name localhost;

        # LuxStudio API
        location /api/lux/ {
            proxy_set_header X-Original-Token $http_authorization;
            proxy_pass http://lux-backend/api/;
        }

        # GISVial API
        location /api/gis/ {
            proxy_set_header X-Original-Token $http_authorization;
            proxy_pass http://gisvial-backend/api/;
        }

        # CORS para desarrollo
        location / {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "Authorization, Content-Type";
            if ($request_method = OPTIONS) { return 204; }
            proxy_pass http://portal;
        }
    }
}
