"""Stable defaults for the first optimizer release."""

DEFAULT_GROUP_FLUX_LM = 897.81
DEFAULT_GROUP_POWER_W = 6.60
DEFAULT_GROUP_LED_COUNT = 3
DEFAULT_CCT_K = 4000
DEFAULT_CRI = 70
DEFAULT_CARRIAGEWAY_WIDTH_M = 3.5
DEFAULT_HEIGHT_M = 1.0
DEFAULT_SPACING_HEIGHT_RATIO = 10.0
DEFAULT_AMBIENT_TEMPERATURE_C = 25.0
DEFAULT_DRIVER_EFFICIENCY = 0.90
DEFAULT_TS_COEFFICIENT_C_PER_W = 0.30
DEFAULT_RTH_JUNCTION_TO_SOLDER_C_PER_W = 1.10
