"""Domain primitives for the SALVI road-lighting LDT designer."""

from .domain import (
    AdjacentBuilding,
    ArrangementType,
    CalculationMetrics,
    IntrusionLimits,
    LuminaireArrangement,
    LuminairePlacement,
    NormativeProfile,
    OptimizationRequest,
    PhotometricCandidate,
    QualityTargets,
    RoadGeometry,
    StreetBand,
)
from .street_geometry import (
    CalculationPoint,
    StreetCalculationGrid,
    SurfaceGrid,
    build_street_calculation_grid,
)
from .direct_illuminance import (
    IlluminanceAtPoint,
    PhotometricAngles,
    direct_illuminance_at_point,
    direct_illuminance_from_luminaire,
    evaluate_direct_illuminance,
    intensity_cd_per_klm,
    photometric_angles,
)
from .road_luminance import (
    ObserverLuminanceResult,
    RoadLuminanceAtPoint,
    RoadObserver,
    StreetLuminanceResult,
    build_lane_observers,
    deviation_angle_beta,
    evaluate_road_luminance_for_observer,
    evaluate_street_luminance,
    luminance_from_luminaire,
    road_luminance_at_point,
    summarize_observer_luminance,
)
from .rtables import BETA_COLS, METADATA, TAN_EPSILON_ROWS, list_tables, r_value
from .edge_metrics import (
    EdgeIlluminanceResult,
    EdgeStripGrid,
    build_edge_strip_grid,
    evaluate_edge_illuminance,
    summarize_edge_illuminance,
)
from .glare import (
    StreetThresholdIncrementResult,
    ThresholdIncrementResult,
    VeilingLuminanceContribution,
    angle_from_line_of_sight_deg,
    build_threshold_increment_observers,
    calculate_threshold_increment,
    eye_illuminance_from_luminaire,
    line_of_sight_unit_vector,
    evaluate_street_threshold_increment,
    veiling_luminance_contribution,
)
from .photometric_symmetry import (
    is_longitudinally_symmetric,
    longitudinal_mirror_c_deg,
    longitudinal_symmetry_error,
    symmetrize_longitudinal,
    validate_longitudinal_symmetry,
)
from .periodic import repeat_luminaire_pattern
from .evaluator import CandidateEvaluation, EvaluationOptions, evaluate_candidate
from .candidate_generator import (
    DEFAULT_RESOLUTION_STAGES,
    AngularResolutionStage,
    PhotometricFamilyParameters,
    generate_resolution_pyramid,
    generate_symmetric_candidate,
    integrated_flux_lm_per_klm,
)
from .lighting_classes import (
    M_LIGHTING_CLASSES,
    MLightingClass,
    get_m_lighting_class,
    list_m_lighting_classes,
)
from .objective import (
    ConstraintPenalty,
    ObjectiveScore,
    ObjectiveWeights,
    score_candidate,
)
from .eulumdat import candidate_from_ldt_text, candidate_to_ldt, read_ldt
from .photometric_validation import (
    AngularResidualMap,
    CompensationResult,
    PhotometricComparison,
    PhotometricDescriptor,
    angular_residual_map,
    compare_photometries,
    compensate_target,
    describe_photometry,
)
from .optimizer import (
    OptimizationConfig,
    OptimizationResult,
    OptimizationTrial,
    PhotometricSearchSpace,
    optimize_candidate,
)

__all__ = [
    "AdjacentBuilding",
    "ArrangementType",
    "CalculationMetrics",
    "IntrusionLimits",
    "LuminaireArrangement",
    "LuminairePlacement",
    "NormativeProfile",
    "OptimizationRequest",
    "PhotometricCandidate",
    "QualityTargets",
    "RoadGeometry",
    "StreetBand",
    "CalculationPoint",
    "StreetCalculationGrid",
    "SurfaceGrid",
    "build_street_calculation_grid",
    "IlluminanceAtPoint",
    "PhotometricAngles",
    "direct_illuminance_at_point",
    "direct_illuminance_from_luminaire",
    "evaluate_direct_illuminance",
    "intensity_cd_per_klm",
    "photometric_angles",
    "ObserverLuminanceResult",
    "RoadLuminanceAtPoint",
    "RoadObserver",
    "StreetLuminanceResult",
    "build_lane_observers",
    "deviation_angle_beta",
    "evaluate_road_luminance_for_observer",
    "evaluate_street_luminance",
    "luminance_from_luminaire",
    "road_luminance_at_point",
    "summarize_observer_luminance",
    "BETA_COLS",
    "METADATA",
    "TAN_EPSILON_ROWS",
    "list_tables",
    "r_value",
    "EdgeIlluminanceResult",
    "EdgeStripGrid",
    "build_edge_strip_grid",
    "evaluate_edge_illuminance",
    "summarize_edge_illuminance",
    "ThresholdIncrementResult",
    "StreetThresholdIncrementResult",
    "VeilingLuminanceContribution",
    "angle_from_line_of_sight_deg",
    "build_threshold_increment_observers",
    "calculate_threshold_increment",
    "eye_illuminance_from_luminaire",
    "line_of_sight_unit_vector",
    "evaluate_street_threshold_increment",
    "veiling_luminance_contribution",
    "is_longitudinally_symmetric",
    "longitudinal_mirror_c_deg",
    "longitudinal_symmetry_error",
    "symmetrize_longitudinal",
    "validate_longitudinal_symmetry",
    "repeat_luminaire_pattern",
    "CandidateEvaluation",
    "EvaluationOptions",
    "evaluate_candidate",
    "PhotometricFamilyParameters",
    "AngularResolutionStage",
    "DEFAULT_RESOLUTION_STAGES",
    "generate_symmetric_candidate",
    "generate_resolution_pyramid",
    "integrated_flux_lm_per_klm",
    "M_LIGHTING_CLASSES",
    "MLightingClass",
    "get_m_lighting_class",
    "list_m_lighting_classes",
    "ConstraintPenalty",
    "ObjectiveScore",
    "ObjectiveWeights",
    "score_candidate",
    "candidate_from_ldt_text",
    "candidate_to_ldt",
    "read_ldt",
    "AngularResidualMap",
    "CompensationResult",
    "PhotometricComparison",
    "PhotometricDescriptor",
    "angular_residual_map",
    "compare_photometries",
    "compensate_target",
    "describe_photometry",
    "OptimizationConfig",
    "OptimizationResult",
    "OptimizationTrial",
    "PhotometricSearchSpace",
    "optimize_candidate",
]
