"""EULUMDAT reader and writer for road-lighting I-tables.

The implementation follows the fixed L1-L26 EULUMDAT header, supports all
standard C-plane symmetry codes on import and keeps intensities in cd/klm.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

from .domain import PhotometricCandidate


def _number(value: float) -> str:
    return f"{float(value):.8g}"


def _step(values: tuple[float, ...], name: str) -> float:
    if len(values) < 2:
        raise ValueError(f"se necesitan al menos dos valores para {name}")
    steps = [round(values[i + 1] - values[i], 7) for i in range(len(values) - 1)]
    if any(step <= 0 for step in steps):
        raise ValueError(f"los ángulos {name} deben ser estrictamente crecientes")
    if len(set(steps)) != 1:
        raise ValueError(f"la malla {name} debe ser equidistante")
    return float(steps[0])


def candidate_to_ldt(
    candidate: PhotometricCandidate,
    filename: str = "generated.ldt",
) -> str:
    """Serialize a full C-table using the standard EULUMDAT record order."""

    if candidate.symmetry != 0:
        raise ValueError("el escritor requiere una tabla C completa (symmetry=0)")

    c_angles = tuple(float(value) for value in candidate.c_angles_deg)
    gamma_angles = tuple(float(value) for value in candidate.gamma_angles_deg)
    dc = _step(c_angles, "C")
    dg = _step(gamma_angles, "gamma")

    lines = [
        candidate.manufacturer,  # L1
        "1",  # L2: point-source luminaire
        "0",  # L3: no symmetry reduction
        str(len(c_angles)),  # L4
        _number(dc),  # L5
        str(len(gamma_angles)),  # L6
        _number(dg),  # L7
        "Generated by SALVI Road LDT Designer",  # L8
        candidate.luminaire_name,  # L9
        "",  # L10 luminaire number
        filename,  # L11
        date.today().isoformat(),  # L12
        "100",  # L13 luminaire length
        "100",  # L14 luminaire width
        "100",  # L15 luminaire height
        "100",  # L16 luminous-area length
        "100",  # L17 luminous-area width
        "0",  # L18 luminous-area height C0
        "0",  # L19 luminous-area height C90
        "0",  # L20 luminous-area height C180
        "0",  # L21 luminous-area height C270
        "0",  # L22 downward-flux fraction
        "100",  # L23 light-output ratio
        "1",  # L24 conversion factor
        "0",  # L25 tilt
        "1",  # L26 number of lamp sets
        "1",  # lamps in set
        candidate.luminaire_name,
        _number(candidate.flux_lm),
        "4000K",
        "70",
        "0",
    ]

    # Ten direct-ratio values required after all lamp-set records.
    lines.extend(["0"] * 10)
    lines.extend(_number(value) for value in c_angles)
    lines.extend(_number(value) for value in gamma_angles)
    for row in candidate.intensity_cd_per_klm:
        lines.extend(_number(value) for value in row)
    return "\n".join(lines) + "\n"


class _LineReader:
    def __init__(self, text: str) -> None:
        self.lines = text.replace("\x00", "").splitlines()
        self.index = 0

    def exact(self) -> str:
        if self.index >= len(self.lines):
            raise ValueError("fichero EULUMDAT incompleto")
        value = self.lines[self.index].strip()
        self.index += 1
        return value

    def non_blank(self) -> str:
        while self.index < len(self.lines):
            value = self.exact()
            if value:
                return value
        raise ValueError("fichero EULUMDAT incompleto")

    def number(self) -> float:
        value = self.non_blank().replace(",", ".")
        try:
            return float(value)
        except ValueError as error:
            raise ValueError(f"valor EULUMDAT no numérico: {value!r}") from error

    def numbers(self, count: int) -> tuple[float, ...]:
        values: list[float] = []
        while len(values) < count:
            for token in self.non_blank().split():
                try:
                    values.append(float(token.replace(",", ".")))
                except ValueError as error:
                    raise ValueError(
                        f"valor EULUMDAT no numérico: {token!r}"
                    ) from error
                if len(values) == count:
                    break
        return tuple(values)


def _interpolate_row(
    c_angles: tuple[float, ...],
    rows: tuple[tuple[float, ...], ...],
    c_deg: float,
) -> tuple[float, ...]:
    if len(c_angles) == 1:
        return rows[0]
    value = min(max(float(c_deg), c_angles[0]), c_angles[-1])
    upper = next(
        (index for index, angle in enumerate(c_angles) if angle >= value),
        len(c_angles) - 1,
    )
    if upper == 0:
        return rows[0]
    lower = upper - 1
    span = c_angles[upper] - c_angles[lower]
    weight = (value - c_angles[lower]) / span if span > 0 else 0.0
    return tuple(
        (1.0 - weight) * rows[lower][index] + weight * rows[upper][index]
        for index in range(len(rows[0]))
    )


def _stored_row_count(symmetry: int, c_count: int) -> int:
    if symmetry == 0:
        return c_count
    if symmetry == 1:
        return 1
    if symmetry in (2, 3):
        return c_count // 2 + 1
    if symmetry == 4:
        return c_count // 4 + 1
    raise ValueError(f"código de simetría EULUMDAT no válido: {symmetry}")


def _expand_c_symmetry(
    symmetry: int,
    full_c_angles: tuple[float, ...],
    stored_rows: tuple[tuple[float, ...], ...],
    nominal_step_deg: float,
) -> tuple[tuple[float, ...], tuple[tuple[float, ...], ...]]:
    if symmetry == 0:
        return full_c_angles, stored_rows
    step = (
        full_c_angles[1] - full_c_angles[0]
        if len(full_c_angles) > 1
        else nominal_step_deg
    )
    if step <= 0 or abs(360.0 / step - round(360.0 / step)) > 1e-7:
        raise ValueError("la reducción de simetría requiere un paso C válido")
    full_angles = tuple(index * step for index in range(len(full_c_angles)))
    if symmetry == 1:
        return full_angles, tuple(stored_rows[0] for _ in full_angles)

    if symmetry == 2:
        source_angles = full_c_angles[: len(stored_rows)]
    elif symmetry == 3:
        quarter = len(full_c_angles) * 3 // 4
        source_angles = tuple(
            angle - 360.0 for angle in full_c_angles[quarter:]
        ) + full_c_angles[: len(full_c_angles) // 4 + 1]
    else:  # symmetry == 4
        source_angles = full_c_angles[: len(stored_rows)]

    full_rows: list[tuple[float, ...]] = []
    for c_deg in full_angles:
        if symmetry == 2:
            source = c_deg if c_deg <= 180.0 else 360.0 - c_deg
        elif symmetry == 3:
            if c_deg <= 90.0:
                source = c_deg
            elif c_deg >= 270.0:
                source = c_deg - 360.0
            else:
                source = 180.0 - c_deg
        else:
            if c_deg <= 90.0:
                source = c_deg
            elif c_deg <= 180.0:
                source = 180.0 - c_deg
            elif c_deg <= 270.0:
                source = c_deg - 180.0
            else:
                source = 360.0 - c_deg
        full_rows.append(_interpolate_row(source_angles, stored_rows, source))
    return full_angles, tuple(full_rows)


def candidate_from_ldt_text(text: str) -> PhotometricCandidate:
    """Read a standard EULUMDAT file and expand its C-plane symmetry."""

    reader = _LineReader(text)
    manufacturer = reader.non_blank()
    reader.number()  # luminaire type
    symmetry = int(reader.number())
    c_count = int(reader.number())
    c_step = reader.number()
    gamma_count = int(reader.number())
    reader.number()  # gamma step; explicit angles remain authoritative
    reader.exact()  # measurement report
    luminaire_name = reader.exact() or "Imported EULUMDAT candidate"
    reader.exact()  # luminaire number
    filename = reader.exact()
    reader.exact()  # date/user

    for _ in range(9):  # L13-L21 dimensions
        reader.number()
    reader.number()  # DFF
    reader.number()  # LORL
    reader.number()  # conversion factor
    reader.number()  # tilt

    lamp_sets = int(reader.number())
    if lamp_sets < 1:
        raise ValueError("el EULUMDAT debe declarar al menos un conjunto de lámparas")
    flux_lm = 0.0
    for _ in range(lamp_sets):
        reader.number()  # number of lamps; flux field is the set total
        reader.exact()  # lamp type; Photopia may leave this text field blank
        lamp_flux_lm = reader.number()
        flux_lm += lamp_flux_lm
        reader.exact()  # colour/CCT; optional text field
        reader.exact()  # CRI; optional text field
        reader.number()  # power
    if flux_lm <= 0:
        raise ValueError("el flujo declarado en el EULUMDAT debe ser positivo")

    reader.numbers(10)  # direct ratios
    c_angles = reader.numbers(c_count)
    gamma_angles = reader.numbers(gamma_count)
    stored_c_count = _stored_row_count(symmetry, c_count)
    flat = reader.numbers(stored_c_count * gamma_count)
    rows = tuple(
        tuple(flat[index * gamma_count : (index + 1) * gamma_count])
        for index in range(stored_c_count)
    )
    full_c_angles, full_rows = _expand_c_symmetry(
        symmetry,
        c_angles,
        rows,
        c_step,
    )
    return PhotometricCandidate(
        c_angles_deg=full_c_angles,
        gamma_angles_deg=gamma_angles,
        intensity_cd_per_klm=full_rows,
        flux_lm=flux_lm,
        manufacturer=manufacturer,
        luminaire_name=luminaire_name,
        symmetry=0,
        metadata={
            "source": "EULUMDAT",
            "filename": filename,
            "original_symmetry": symmetry,
        },
    )


def write_ldt(
    path: str | Path,
    candidate: PhotometricCandidate,
    filename: str | None = None,
) -> Path:
    """Write and return an LDT path using latin-1 compatible text."""

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    name = filename or output.name
    output.write_text(candidate_to_ldt(candidate, name), encoding="latin-1")
    return output


def read_ldt(path: str | Path) -> PhotometricCandidate:
    """Read one standard EULUMDAT file."""

    return candidate_from_ldt_text(Path(path).read_text(encoding="latin-1"))
