*
!Diseño tuneles legacy/
!Diseño tuneles legacy/app.py
!Diseño tuneles legacy/config.py
!Diseño tuneles legacy/requirements.txt
!Diseño tuneles legacy/modules/
!Diseño tuneles legacy/modules/**
!Diseño tuneles legacy/templates/
!Diseño tuneles legacy/templates/**
!Diseño tuneles legacy/static/
!Diseño tuneles legacy/static/**
!Diseño tuneles legacy/assets/
!Diseño tuneles legacy/assets/**
!Diseño tuneles legacy/photometric_engine/
!Diseño tuneles legacy/photometric_engine/**
!Diseño tuneles legacy/APHEX S-ES.pdf
!Diseño tuneles legacy/APHEX M-ES.pdf
!Diseño tuneles legacy/APHEX L-ES.pdf
